# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-21 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=32, verbose_name='\u7ec4\u540d')),
                ('host_name', models.GenericIPAddressField(verbose_name='\u4e3b\u673a\u540d')),
                ('ansible_ssh_user', models.CharField(default='root', max_length=32, verbose_name='\u8fde\u63a5\u88ab\u7ba1\u7406\u4e3b\u673a\u7684\u7528\u6237')),
                ('ansible_ssh_pass', models.CharField(blank=True, max_length=64, null=True, verbose_name='\u8fde\u63a5\u88ab\u7ba1\u7406\u4e3b\u673a\u7684\u5bc6\u7801')),
                ('ansible_ssh_port', models.IntegerField(default=22, verbose_name='\u88ab\u7ba1\u7406\u4e3b\u673a\u7684SSH\u7aef\u53e3\u53f7')),
                ('ansible_sudo', models.CharField(blank=True, max_length=32, null=True, verbose_name='\u662f\u5426\u542f\u52a8sudo')),
                ('ansible_sudo_pass', models.CharField(blank=True, max_length=64, null=True, verbose_name='sudo\u5bc6\u7801')),
                ('ansible_sudo_exe', models.CharField(blank=True, max_length=128, null=True, verbose_name='sudo\u8def\u5f84')),
                ('ansible_connection', models.CharField(blank=True, max_length=32, null=True, verbose_name='ssh\u8fde\u63a5\u65b9\u5f0f')),
                ('ansible_ssh_key', models.CharField(blank=True, max_length=16, null=True, verbose_name='ssh\u7684key\u540d\u79f0')),
                ('ansible_shell_type', models.CharField(blank=True, max_length=16, null=True, verbose_name='\u88ab\u7ba1\u7406\u4e3b\u673a\u7684shell\u7c7b\u578b')),
                ('ansible_python_interpreter', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u88ab\u88ab\u7ba1\u7406\u4e3b\u673a\u7684python\u7f16\u8bd1\u5668\u8def\u5f84')),
                ('ansible_other_interpreter', models.CharField(blank=True, max_length=128, null=True, verbose_name='\u88ab\u7ba1\u7406\u4e3b\u673a\u7684\u5176\u4ed6\u7f16\u8bd1\u5668\u8def\u5f84\uff0c\u672a\u4f7f\u7528')),
            ],
            options={
                'db_table': 'hosts',
                'verbose_name_plural': 'inventory\u8868',
            },
        ),
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('key_name', models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='\u5bc6\u94a5\u540d')),
                ('private_key', models.TextField(blank=True, null=True, verbose_name='\u5bc6\u94a5\u5185\u5bb9')),
                ('public_key', models.TextField(blank=True, null=True, verbose_name='\u516c\u94a5\u5185\u5bb9')),
            ],
            options={
                'db_table': 'private_key',
                'verbose_name_plural': 'private_key\u8868',
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operate_program', models.CharField(max_length=40, verbose_name='\u53ef\u64cd\u4f5c\u5e94\u7528')),
            ],
            options={
                'verbose_name_plural': '\u53ef\u9009\u5e94\u7528\u8868',
            },
        ),
        migrations.AlterUniqueTogether(
            name='hosts',
            unique_together=set([('group_name', 'host_name')]),
        ),
    ]
